/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogosRouteImport } from './routes/logos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRewritePromptRouteImport } from './routes/api/rewrite-prompt'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const LogosRoute = LogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewritePromptRoute = ApiRewritePromptRouteImport.update({
  id: '/api/rewrite-prompt',
  path: '/api/rewrite-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logos': typeof LogosRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/rewrite-prompt': typeof ApiRewritePromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logos': typeof LogosRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/rewrite-prompt': typeof ApiRewritePromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logos': typeof LogosRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/rewrite-prompt': typeof ApiRewritePromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logos' | '/api/generate-image' | '/api/rewrite-prompt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logos' | '/api/generate-image' | '/api/rewrite-prompt'
  id:
    | '__root__'
    | '/'
    | '/logos'
    | '/api/generate-image'
    | '/api/rewrite-prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogosRoute: typeof LogosRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiRewritePromptRoute: typeof ApiRewritePromptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewrite-prompt': {
      id: '/api/rewrite-prompt'
      path: '/api/rewrite-prompt'
      fullPath: '/api/rewrite-prompt'
      preLoaderRoute: typeof ApiRewritePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogosRoute: LogosRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiRewritePromptRoute: ApiRewritePromptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
