/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRewritePromptRouteImport } from './routes/api/rewrite-prompt'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewritePromptRoute = ApiRewritePromptRouteImport.update({
  id: '/api/rewrite-prompt',
  path: '/api/rewrite-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/rewrite-prompt': typeof ApiRewritePromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/rewrite-prompt': typeof ApiRewritePromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/rewrite-prompt': typeof ApiRewritePromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate-image' | '/api/rewrite-prompt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate-image' | '/api/rewrite-prompt'
  id: '__root__' | '/' | '/api/generate-image' | '/api/rewrite-prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiRewritePromptRoute: typeof ApiRewritePromptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewrite-prompt': {
      id: '/api/rewrite-prompt'
      path: '/api/rewrite-prompt'
      fullPath: '/api/rewrite-prompt'
      preLoaderRoute: typeof ApiRewritePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiRewritePromptRoute: ApiRewritePromptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
